"""
UE5 Source Query Tool - GUI Management Interface

Provides a graphical interface for managing:
- Configuration settings (.env file)
- Indexed directories
- Vector store rebuilding
- Installation updates
"""

import tkinter as tk
from tkinter import ttk, filedialog, messagebox, scrolledtext
import os
import sys
from pathlib import Path
import subprocess
import threading
from typing import List, Optional

# Get script directory
SCRIPT_DIR = Path(__file__).parent.parent.parent
CONFIG_FILE = SCRIPT_DIR / "config" / ".env"
DIRS_FILE = SCRIPT_DIR / "config" / "indexed_directories.txt"


class ConfigManager:
    """Manages .env configuration file"""

    def __init__(self, config_path: Path):
        self.config_path = config_path
        self.config = {}
        self.load()

    def load(self):
        """Load configuration from .env file"""
        if not self.config_path.exists():
            return

        with open(self.config_path, 'r') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    self.config[key.strip()] = value.strip()

    def save(self):
        """Save configuration to .env file"""
        if not self.config_path.parent.exists():
            self.config_path.parent.mkdir(parents=True)

        with open(self.config_path, 'w') as f:
            f.write("# UE5 Source Query Tool Configuration\n")
            f.write("# Auto-generated by GUI Manager\n\n")

            for key, value in self.config.items():
                f.write(f"{key}={value}\n")

    def get(self, key: str, default: str = "") -> str:
        """Get configuration value"""
        return self.config.get(key, default)

    def set(self, key: str, value: str):
        """Set configuration value"""
        self.config[key] = value


class DirectoryManager:
    """Manages indexed directories list"""

    def __init__(self, dirs_file: Path):
        self.dirs_file = dirs_file
        self.directories: List[str] = []
        self.load()

    def load(self):
        """Load directories from file"""
        if not self.dirs_file.exists():
            return

        with open(self.dirs_file, 'r') as f:
            self.directories = [line.strip() for line in f if line.strip()]

    def save(self):
        """Save directories to file"""
        if not self.dirs_file.parent.exists():
            self.dirs_file.parent.mkdir(parents=True)

        with open(self.dirs_file, 'w') as f:
            for directory in self.directories:
                f.write(f"{directory}\n")

    def add(self, directory: str) -> bool:
        """Add directory if not already present"""
        if directory not in self.directories:
            self.directories.append(directory)
            self.save()
            return True
        return False

    def remove(self, directory: str) -> bool:
        """Remove directory if present"""
        if directory in self.directories:
            self.directories.remove(directory)
            self.save()
            return True
        return False


class ManagerGUI:
    """Main GUI application"""

    def __init__(self, root: tk.Tk):
        self.root = root
        self.root.title("UE5 Source Query - Management Tool")
        self.root.geometry("800x600")

        self.config_manager = ConfigManager(CONFIG_FILE)
        self.dir_manager = DirectoryManager(DIRS_FILE)

        self.create_widgets()
        self.load_data()

    def create_widgets(self):
        """Create GUI widgets"""
        # Create notebook (tabbed interface)
        self.notebook = ttk.Notebook(self.root)
        self.notebook.pack(fill=tk.BOTH, expand=True, padx=5, pady=5)

        # Configuration tab
        self.config_frame = ttk.Frame(self.notebook)
        self.notebook.add(self.config_frame, text="Configuration")
        self.create_config_tab()

        # Directories tab
        self.dirs_frame = ttk.Frame(self.notebook)
        self.notebook.add(self.dirs_frame, text="Indexed Directories")
        self.create_dirs_tab()

        # Actions tab
        self.actions_frame = ttk.Frame(self.notebook)
        self.notebook.add(self.actions_frame, text="Actions")
        self.create_actions_tab()

    def create_config_tab(self):
        """Create configuration tab"""
        frame = ttk.Frame(self.config_frame, padding=10)
        frame.pack(fill=tk.BOTH, expand=True)

        # API Key
        ttk.Label(frame, text="Anthropic API Key:", font=('Arial', 10, 'bold')).grid(row=0, column=0, sticky=tk.W, pady=5)
        self.api_key_var = tk.StringVar()
        api_key_entry = ttk.Entry(frame, textvariable=self.api_key_var, width=60, show="*")
        api_key_entry.grid(row=1, column=0, columnspan=2, sticky=tk.EW, pady=5)

        # Vector Output Dir
        ttk.Label(frame, text="Vector Store Directory:", font=('Arial', 10, 'bold')).grid(row=2, column=0, sticky=tk.W, pady=5)
        self.vector_dir_var = tk.StringVar()
        ttk.Entry(frame, textvariable=self.vector_dir_var, width=50).grid(row=3, column=0, sticky=tk.EW, pady=5)
        ttk.Button(frame, text="Browse...", command=self.browse_vector_dir).grid(row=3, column=1, padx=5)

        # Embedding Model
        ttk.Label(frame, text="Embedding Model:", font=('Arial', 10, 'bold')).grid(row=4, column=0, sticky=tk.W, pady=5)
        self.embed_model_var = tk.StringVar()
        embed_combo = ttk.Combobox(frame, textvariable=self.embed_model_var, width=57, state='readonly')
        embed_combo['values'] = ('microsoft/unixcoder-base', 'sentence-transformers/all-MiniLM-L6-v2')
        embed_combo.grid(row=5, column=0, columnspan=2, sticky=tk.EW, pady=5)

        # API Model
        ttk.Label(frame, text="Claude API Model:", font=('Arial', 10, 'bold')).grid(row=6, column=0, sticky=tk.W, pady=5)
        self.api_model_var = tk.StringVar()
        api_model_combo = ttk.Combobox(frame, textvariable=self.api_model_var, width=57, state='readonly')
        api_model_combo['values'] = ('claude-3-haiku-20240307', 'claude-3-5-sonnet-20241022', 'claude-3-opus-20240229')
        api_model_combo.grid(row=7, column=0, columnspan=2, sticky=tk.EW, pady=5)

        # Save button
        ttk.Button(frame, text="Save Configuration", command=self.save_config, style='Accent.TButton').grid(row=8, column=0, columnspan=2, pady=20)

        frame.columnconfigure(0, weight=1)

    def create_dirs_tab(self):
        """Create directories tab"""
        frame = ttk.Frame(self.dirs_frame, padding=10)
        frame.pack(fill=tk.BOTH, expand=True)

        # Listbox with scrollbar
        list_frame = ttk.Frame(frame)
        list_frame.pack(fill=tk.BOTH, expand=True, pady=5)

        scrollbar = ttk.Scrollbar(list_frame)
        scrollbar.pack(side=tk.RIGHT, fill=tk.Y)

        self.dirs_listbox = tk.Listbox(list_frame, yscrollcommand=scrollbar.set, font=('Courier', 9))
        self.dirs_listbox.pack(side=tk.LEFT, fill=tk.BOTH, expand=True)
        scrollbar.config(command=self.dirs_listbox.yview)

        # Buttons
        button_frame = ttk.Frame(frame)
        button_frame.pack(fill=tk.X, pady=5)

        ttk.Button(button_frame, text="Add Directory", command=self.add_directory).pack(side=tk.LEFT, padx=5)
        ttk.Button(button_frame, text="Remove Selected", command=self.remove_directory).pack(side=tk.LEFT, padx=5)
        ttk.Button(button_frame, text="Refresh List", command=self.refresh_dirs_list).pack(side=tk.LEFT, padx=5)

    def create_actions_tab(self):
        """Create actions tab"""
        frame = ttk.Frame(self.actions_frame, padding=10)
        frame.pack(fill=tk.BOTH, expand=True)

        # Action buttons
        ttk.Label(frame, text="Management Actions", font=('Arial', 12, 'bold')).pack(pady=10)

        ttk.Button(frame, text="Rebuild Vector Index", command=self.rebuild_index, width=30).pack(pady=5)
        ttk.Label(frame, text="Rebuild the entire vector store from configured directories", font=('Arial', 8)).pack()

        ttk.Separator(frame, orient=tk.HORIZONTAL).pack(fill=tk.X, pady=15)

        ttk.Button(frame, text="Update Installation", command=self.update_installation, width=30).pack(pady=5)
        ttk.Label(frame, text="Update source files from main repository", font=('Arial', 8)).pack()

        ttk.Separator(frame, orient=tk.HORIZONTAL).pack(fill=tk.X, pady=15)

        ttk.Button(frame, text="Run Configuration Wizard", command=self.run_configure, width=30).pack(pady=5)
        ttk.Label(frame, text="Interactive setup wizard (terminal)", font=('Arial', 8)).pack()

        # Output log
        ttk.Label(frame, text="Output Log:", font=('Arial', 10, 'bold')).pack(pady=(20, 5))
        self.log_text = scrolledtext.ScrolledText(frame, height=10, state=tk.DISABLED, bg='#1e1e1e', fg='#d4d4d4', font=('Courier', 9))
        self.log_text.pack(fill=tk.BOTH, expand=True, pady=5)

    def log(self, message: str):
        """Add message to log"""
        self.log_text.config(state=tk.NORMAL)
        self.log_text.insert(tk.END, f"{message}\n")
        self.log_text.see(tk.END)
        self.log_text.config(state=tk.DISABLED)

    def load_data(self):
        """Load data into GUI"""
        # Load configuration
        self.api_key_var.set(self.config_manager.get('ANTHROPIC_API_KEY'))
        self.vector_dir_var.set(self.config_manager.get('VECTOR_OUTPUT_DIR', str(SCRIPT_DIR / 'data')))
        self.embed_model_var.set(self.config_manager.get('EMBED_MODEL', 'microsoft/unixcoder-base'))
        self.api_model_var.set(self.config_manager.get('ANTHROPIC_MODEL', 'claude-3-haiku-20240307'))

        # Load directories
        self.refresh_dirs_list()

    def save_config(self):
        """Save configuration"""
        self.config_manager.set('ANTHROPIC_API_KEY', self.api_key_var.get())
        self.config_manager.set('VECTOR_OUTPUT_DIR', self.vector_dir_var.get())
        self.config_manager.set('PYTHONPATH', str(SCRIPT_DIR / '.venv' / 'Lib' / 'site-packages'))
        self.config_manager.set('EMBED_MODEL', self.embed_model_var.get())
        self.config_manager.set('ANTHROPIC_MODEL', self.api_model_var.get())
        self.config_manager.save()

        messagebox.showinfo("Success", "Configuration saved successfully!")
        self.log("Configuration saved")

    def browse_vector_dir(self):
        """Browse for vector store directory"""
        directory = filedialog.askdirectory(initialdir=self.vector_dir_var.get())
        if directory:
            self.vector_dir_var.set(directory)

    def add_directory(self):
        """Add directory to index"""
        directory = filedialog.askdirectory(title="Select Directory to Index")
        if directory:
            if self.dir_manager.add(directory):
                self.refresh_dirs_list()
                self.log(f"Added directory: {directory}")
                messagebox.showinfo("Success", f"Directory added:\n{directory}")
            else:
                messagebox.showwarning("Already Exists", "Directory is already in the list")

    def remove_directory(self):
        """Remove selected directory"""
        selection = self.dirs_listbox.curselection()
        if not selection:
            messagebox.showwarning("No Selection", "Please select a directory to remove")
            return

        index = selection[0]
        directory = self.dir_manager.directories[index]

        if messagebox.askyesno("Confirm Removal", f"Remove this directory?\n\n{directory}"):
            self.dir_manager.remove(directory)
            self.refresh_dirs_list()
            self.log(f"Removed directory: {directory}")

    def refresh_dirs_list(self):
        """Refresh directories listbox"""
        self.dir_manager.load()
        self.dirs_listbox.delete(0, tk.END)
        for directory in self.dir_manager.directories:
            self.dirs_listbox.insert(tk.END, directory)

    def rebuild_index(self):
        """Rebuild vector index"""
        if not self.dir_manager.directories:
            messagebox.showwarning("No Directories", "Please add directories to index first")
            return

        if not messagebox.askyesno("Confirm Rebuild", "Rebuild the entire vector index?\n\nThis may take 2-3 minutes with GPU or 30-40 minutes with CPU."):
            return

        self.log("Starting vector index rebuild...")
        self.log(f"Indexing {len(self.dir_manager.directories)} directories")

        # Run rebuild in thread to avoid blocking GUI
        def run_rebuild():
            script = str(SCRIPT_DIR / "rebuild-index.bat")
            process = subprocess.Popen([script, "--force", "--verbose"],
                                      stdout=subprocess.PIPE,
                                      stderr=subprocess.STDOUT,
                                      text=True,
                                      cwd=str(SCRIPT_DIR))

            for line in process.stdout:
                self.root.after(0, self.log, line.strip())

            process.wait()
            if process.returncode == 0:
                self.root.after(0, messagebox.showinfo, "Success", "Vector index rebuilt successfully!")
            else:
                self.root.after(0, messagebox.showerror, "Error", "Index rebuild failed. Check log for details.")

        threading.Thread(target=run_rebuild, daemon=True).start()

    def update_installation(self):
        """Update installation from main repo"""
        self.log("Starting installation update...")

        def run_update():
            script = str(SCRIPT_DIR / "update.bat")
            process = subprocess.Popen([script],
                                      stdout=subprocess.PIPE,
                                      stderr=subprocess.STDOUT,
                                      text=True,
                                      cwd=str(SCRIPT_DIR))

            for line in process.stdout:
                self.root.after(0, self.log, line.strip())

            process.wait()
            if process.returncode == 0:
                self.root.after(0, messagebox.showinfo, "Success", "Installation updated successfully!")
            else:
                self.root.after(0, messagebox.showerror, "Error", "Update failed. Check log for details.")

        threading.Thread(target=run_update, daemon=True).start()

    def run_configure(self):
        """Run configuration wizard in terminal"""
        self.log("Launching configuration wizard in terminal...")
        script = str(SCRIPT_DIR / "configure.bat")
        subprocess.Popen(['start', 'cmd', '/k', script], shell=True, cwd=str(SCRIPT_DIR))


def main():
    root = tk.Tk()
    app = ManagerGUI(root)
    root.mainloop()


if __name__ == "__main__":
    main()
