import os
from pathlib import Path
from src.utils.file_utils import atomic_write

class ConfigManager:
    """Helper to manage config/.env file"""
    def __init__(self, script_dir):
        self.config_file = script_dir / "config" / ".env"
        self._config = {}
        self.load()

    def load(self):
        self._config.clear()
        if not self.config_file.exists():
            return

        with open(self.config_file, 'r') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    self._config[key.strip()] = value.strip()

    def save(self, config_dict):
        self.config_file.parent.mkdir(parents=True, exist_ok=True)
        with atomic_write(self.config_file, 'w') as f:
            f.write("# UE5 Source Query Tool Configuration\n")
            f.write("# Auto-generated by Dashboard\n\n")
            for key, value in config_dict.items():
                f.write(f"{key}={value}\n")
        self.load() # Reload after saving

    def get(self, key, default=None):
        return self._config.get(key, default)

    def set(self, key, value):
        self._config[key] = value
